version: '2'
services:
    project_taa_gli-app:
        image: project_taa_gli
        external_links:
            - project_taa_gli-mysql:mysql
            - project_taa_gli-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/project_taa_gli?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    project_taa_gli-mysql:
        extends:
            file: mysql.yml
            service: project_taa_gli-mysql
    project_taa_gli-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: project_taa_gli-elasticsearch
